package org.example.fullcycle

object PipelineEmoji {
    const val SUCCESS = "✅"
    const val ERROR = "❌"
    const val IN_PROGRESS = "⏳"
    const val WAITING = "⏸️"
    const val SKIPPED = "⏭️"
    const val WARNING = "⚠️"
    const val INFO = "ℹ️"
    const val RUNNING = "🔄"
    const val PENDING = "⏰"
    const val COMPLETED = "✔️"
    const val FAILED = "💥"
    const val CANCELLED = "🚫"
    const val QUEUED = "📋"
    const val BUILDING = "🔨"
    const val TESTING = "🧪"
    const val DEPLOYING = "🚀"
    const val PIPELINE = "📦"
    const val BRANCH = "🌿"
    const val COMMIT = "💾"
    const val MERGE = "🔀"
    const val REVIEW = "👀"
    const val APPROVED = "👍"
    const val REJECTED = "👎"
    const val TIMEOUT = "⏱️"
    const val RETRY = "🔁"
}