package org.example.fullcycle

object PipelineEmoji {
    const val ANALYZING = "🔍"
    const val PLAN = "📋"
    const val CHANGES = "✏️"
    const val BRANCH = "🌿"
    const val COMMIT = "📝"
    const val PUSH = "⬆️"
    const val PR = "🔗"
    const val REVIEW = "🔎"
    const val CI = "⏳"
    const val SUCCESS = "✓"
    const val ERROR = "✗"
    const val WARNING = "⚠️"
    const val MERGE = "🔀"
    const val LOADING = "⌛"
    const val APPROVED = "✅"
    const val REJECTED = "❌"
    const val PENDING = "⏸️"
    const val RUNNING = "🏃"
    const val COMPLETED = "🎉"
    const val CANCELLED = "🚫"
    const val INFO = "ℹ️"
    const val SEARCH = "🔎"
    const val RAG = "📚"
    const val FIX = "🔧"
    const val ITERATE = "🔄"
}